/**
 * Area: Megastructures
 * Plan: tests/docs/areas/megastructures.md
 *
 * Two halves, and they meet in the middle:
 *
 *   1. Ancient manuscripts. These are generated by `extendStarDataRange()` —
 *      the same call the space telescope makes when a star study completes — at
 *      guaranteed thresholds of 5, 20, 35 and 45 light years of star vision.
 *      Driving the real function rather than pushing entries into the array is
 *      what proves the eligibility filtering (no Miaplacidus, no settled star,
 *      no O-type, no repeats) actually holds.
 *
 *   2. Capture. `applyMegaStructureBonuses(structure, tech)` is the single entry
 *      point every megastructure research row calls on unlock, so each of the
 *      four structures' five stages is exercised through it directly.
 *
 * Stage 3 is shared architecture across all four structures: it always knocks
 * the Miaplacidean force field down one level and permanently unlocks
 * antimatter, which is what makes the endgame reachable.
 */
import { test, expect } from '../_harness/game-fixture.mjs';

const STRUCTURE_TECHS = {
  1: ['dysonSphereUnderstanding', 'dysonSphereCapabilities', 'dysonSphereDisconnect', 'dysonSpherePower', 'dysonSphereConnect'],
  2: ['celestialProcessingCoreUnderstanding', 'celestialProcessingCoreCapabilities', 'celestialProcessingCoreDisconnect', 'celestialProcessingCorePower', 'celestialProcessingCoreConnect'],
  3: ['plasmaForgeUnderstanding', 'plasmaForgeCapabilities', 'plasmaForgeDisconnect', 'plasmaForgePower', 'plasmaForgeConnect'],
  4: ['galacticMemoryArchiveUnderstanding', 'galacticMemoryArchiveCapabilities', 'galacticMemoryArchiveDisconnect', 'galacticMemoryArchivePower', 'galacticMemoryArchiveConnect']
};

/**
 * Clear the manuscript survey back to a pristine state.
 *
 * The debug scenario studies stars on the way to a launch-ready run, and that
 * generates manuscripts as a side effect, so every generation case has to start
 * from zero to mean anything. `setStarsWithAncientManuscripts` only pushes and
 * the accessor hands back the live array, so this drains it in place; the
 * factory-star list has an explicit override form.
 */
async function resetSurvey(game) {
  await game.withMods((m) => {
    m.cg.getStarsWithAncientManuscripts().length = 0;
    m.cg.setFactoryStarsArray([], true);
    m.cg.setStarVisionDistance(0);
  });
}

test.describe('Megastructures — ancient manuscripts', () => {
  test.beforeEach(async ({ game }) => {
    await game.boot();
    await game.prepareRunForStarshipLaunch();
  });

  test('reaching five light years of star vision guarantees the first manuscript', async ({ game }) => {
    await resetSurvey(game);

    const result = await game.withMods((m) => {
      const before = m.cg.getStarsWithAncientManuscripts().length;
      // extendStarDataRange advances vision by one increment per call, and the
      // roll is forced to 100% the moment the range crosses 5.
      for (let i = 0; i < 6; i++) m.game.extendStarDataRange(true);

      return {
        before,
        range: m.cg.getStarVisionDistance(),
        manuscripts: m.cg.getStarsWithAncientManuscripts(),
        factoryStars: m.cg.getFactoryStarsArray()
      };
    });

    expect(result.range).toBeGreaterThanOrEqual(5);
    expect(result.manuscripts.length).toBeGreaterThan(result.before);
    expect(result.factoryStars.length).toBeGreaterThan(0);
  });

  test('each manuscript records its star, factory star, position and reported flag', async ({ game }) => {
    await resetSurvey(game);

    const manuscripts = await game.withMods((m) => {
      for (let i = 0; i < 60 && m.cg.getStarsWithAncientManuscripts().length < 4; i++) {
        m.game.extendStarDataRange(true);
      }
      return m.cg.getStarsWithAncientManuscripts();
    });

    expect(manuscripts.length).toBe(4);
    manuscripts.forEach((entry, index) => {
      expect(Array.isArray(entry), `entry ${index} shape`).toBe(true);
      expect(entry.length).toBe(4);
      const [manuscriptStar, factoryStar, position, reported] = entry;
      expect(typeof manuscriptStar).toBe('string');
      expect(manuscriptStar).toBe(manuscriptStar.toLowerCase());
      expect(typeof factoryStar).toBe('string');
      // Position is the manuscript's ordinal, and it selects which factory
      // system the clue points at.
      expect(position).toBe(index + 1);
      expect(reported).toBe(false);
    });
  });

  test('manuscripts stop at the documented maximum and never repeat a star', async ({ game }) => {
    await resetSurvey(game);

    const result = await game.withMods((m) => {
      // Push well past the last guaranteed threshold of 45 light years.
      for (let i = 0; i < 120; i++) m.game.extendStarDataRange(true);

      const manuscripts = m.cg.getStarsWithAncientManuscripts();
      const stars = manuscripts.map((entry) => entry[0]);
      const factoryStars = manuscripts.map((entry) => entry[1]);

      return {
        max: m.cg.getMaxAncientManuscripts(),
        count: manuscripts.length,
        range: m.cg.getStarVisionDistance(),
        uniqueStars: new Set(stars).size,
        uniqueFactoryStars: new Set(factoryStars).size,
        stars,
        factoryStars,
        currentSystem: String(m.cg.getCurrentStarSystem() || '').toLowerCase(),
        settled: (m.cg.getSettledStars() || []).map((s) => String(s).toLowerCase()),
        oTypes: stars.filter((s) => m.desc.getStarTypeByName(s) === 'O')
      };
    });

    expect(result.range).toBeGreaterThan(45);
    expect(result.count).toBe(result.max);
    expect(result.count).toBe(4);
    expect(result.uniqueStars).toBe(4);
    expect(result.uniqueFactoryStars).toBe(4);
    // The generator excludes the home system, anything already settled,
    // Miaplacidus, and O-type stars (which are reserved for power plants).
    expect(result.stars).not.toContain('miaplacidus');
    expect(result.stars).not.toContain(result.currentSystem);
    for (const settled of result.settled) expect(result.stars).not.toContain(settled);
    expect(result.oTypes).toEqual([]);
  });

  test('a manuscript star is never also one of the factory stars it points at', async ({ game }) => {
    await resetSurvey(game);

    const result = await game.withMods((m) => {
      for (let i = 0; i < 120 && m.cg.getStarsWithAncientManuscripts().length < 4; i++) {
        m.game.extendStarDataRange(true);
      }
      const manuscripts = m.cg.getStarsWithAncientManuscripts();
      return {
        stars: manuscripts.map((e) => e[0]),
        factoryStars: manuscripts.map((e) => e[1]),
        registered: m.cg.getFactoryStarsArray()
      };
    });

    for (const star of result.stars) {
      expect(result.factoryStars, `${star} used as its own factory star`).not.toContain(star);
    }
    // Every factory star a manuscript points at is registered globally, so the
    // star map can mark it.
    for (const factoryStar of result.factoryStars) {
      expect(result.registered).toContain(factoryStar);
    }
  });

  test('activating a factory star marks its manuscript as reported', async ({ game }) => {
    await resetSurvey(game);

    const result = await game.withMods((m) => {
      for (let i = 0; i < 60 && m.cg.getStarsWithAncientManuscripts().length < 1; i++) {
        m.game.extendStarDataRange(true);
      }

      const entry = m.cg.getStarsWithAncientManuscripts()[0];
      const before = [...entry];
      m.cg.activateFactoryStar(entry);
      const after = m.cg.getStarsWithAncientManuscripts()[0];

      return { before, after, registered: m.cg.getFactoryStarsArray() };
    });

    expect(result.before[3]).toBe(false);
    expect(result.after[3]).toBe(true);
    expect(result.after[0]).toBe(result.before[0]);
    expect(result.registered).toContain(result.after[1]);
  });

  test('manuscript clue tracking records which clue was shown for which star', async ({ game }) => {
    const result = await game.withMods((m) => {
      m.cg.markManuscriptClueShown('Sirius', 3);
      m.cg.markManuscriptClueShown('sirius', 3);
      m.cg.markManuscriptClueShown('sirius', 7);
      m.cg.markManuscriptClueShown('', 1);
      m.cg.markManuscriptClueShown('rigel', null);
      return m.cg.getManuscriptCluesShown();
    });

    // Star names are normalised to lower case, and a clue is only recorded once
    // so it cannot be re-shown for the same star.
    expect(result.sirius).toEqual([3, 7]);
    expect(result['']).toBeUndefined();
    expect(result.rigel).toBeUndefined();
  });

  test('manuscript and factory-star progress survives a save/load round trip', async ({ game }) => {
    await resetSurvey(game);

    const result = await game.withMods((m) => {
      for (let i = 0; i < 60 && m.cg.getStarsWithAncientManuscripts().length < 2; i++) {
        m.game.extendStarDataRange(true);
      }

      const live = m.cg.getStarsWithAncientManuscripts();
      const saved = JSON.parse(JSON.stringify(m.cg.captureGameStatusForSaving('initialise')));
      return {
        live,
        savedManuscripts: saved.starsWithAncientManuscripts,
        savedFactoryStars: saved.factoryStarsArray,
        liveFactoryStars: m.cg.getFactoryStarsArray()
      };
    });

    expect(result.savedManuscripts).toEqual(result.live);
    expect(result.savedFactoryStars).toEqual(result.liveFactoryStars);
  });
});

test.describe('Megastructures — capture and bonuses', () => {
  test.beforeEach(async ({ game }) => {
    await game.boot();
    await game.prepareRunForStarshipLaunch();
  });

  test('all four structures expose five research stages with rising prices and a prerequisite chain', async ({ game }) => {
    const problems = await game.withMods((m, structures) => {
      const issues = [];
      for (const [structure, techs] of Object.entries(structures)) {
        let previousPrice = 0;
        techs.forEach((techName, index) => {
          const tech = m.rdo.getResourceDataObject('techs', [techName]);
          if (!tech) { issues.push(`${techName}: missing`); return; }
          if (tech.special !== 'megastructure') issues.push(`${techName}: not flagged as a megastructure tech`);
          if (!(tech.price > previousPrice)) issues.push(`${techName}: price ${tech.price} does not exceed ${previousPrice}`);
          previousPrice = tech.price;

          // Every stage after the first chains off the one before it.
          if (index > 0 && tech.appearsAt?.[1] !== techs[index - 1]) {
            issues.push(`${techName}: prerequisite is ${tech.appearsAt?.[1]}, expected ${techs[index - 1]}`);
          }
          if (!Array.isArray(tech.prereqs) || tech.prereqs.length === 0) {
            issues.push(`${techName}: no prereq label`);
          }
        });
        // All four paths are rendered as separate columns in the tech tree.
        const paths = new Set(techs.map((t) => m.rdo.getResourceDataObject('techs', [t])?.path));
        if (paths.size !== 1) issues.push(`structure ${structure}: stages span multiple tech-tree paths`);
      }
      return issues;
    }, STRUCTURE_TECHS);

    expect(problems).toEqual([]);
  });

  test('Dyson Sphere stage 1 doubles every battery capacity and the energy store', async ({ game }) => {
    const result = await game.withMods((m) => {
      const batteries = ['battery1', 'battery2', 'battery3'];
      const read = () => ({
        batteries: batteries.map((b) => m.rdo.getResourceDataObject('buildings', ['energy', 'upgrades', b, 'capacity'])),
        storage: m.rdo.getResourceDataObject('buildings', ['energy', 'storageCapacity'])
      });

      const before = read();
      m.game.applyMegaStructureBonuses(1, 1);
      return { before, after: read(), researched: m.cg.getMegaStructureTechsResearched() };
    });

    result.after.batteries.forEach((capacity, index) => {
      expect(capacity).toBe(Math.floor(result.before.batteries[index] * 2));
    });
    expect(result.after.storage).toBe(Math.floor(result.before.storage * 2));
    expect(result.researched).toContainEqual([1, 1]);
  });

  test('Dyson Sphere stage 2 raises every power plant rate by 25%', async ({ game }) => {
    const result = await game.withMods((m) => {
      const plants = ['powerPlant1', 'powerPlant2', 'powerPlant3'];
      const read = () => plants.map((p) => ({
        rate: m.rdo.getResourceDataObject('buildings', ['energy', 'upgrades', p, 'rate']),
        purchasedRate: m.rdo.getResourceDataObject('buildings', ['energy', 'upgrades', p, 'purchasedRate']),
        maxPurchasedRate: m.rdo.getResourceDataObject('buildings', ['energy', 'upgrades', p, 'maxPurchasedRate'])
      }));

      const before = read();
      m.game.applyMegaStructureBonuses(1, 2);
      return { before, after: read(), researched: m.cg.getMegaStructureTechsResearched() };
    });

    result.after.forEach((plant, index) => {
      expect(plant.rate).toBeCloseTo(result.before[index].rate * 1.25, 6);
      expect(plant.purchasedRate).toBeCloseTo(result.before[index].purchasedRate * 1.25, 6);
      expect(plant.maxPurchasedRate).toBeCloseTo(result.before[index].maxPurchasedRate * 1.25, 6);
    });
    expect(result.researched).toContainEqual([1, 2]);
  });

  test('Dyson Sphere stages 4 and 5 switch on infinite power', async ({ game }) => {
    const result = await game.withMods((m) => {
      m.cg.setInfinitePower(false);
      m.game.applyMegaStructureBonuses(1, 4);
      const afterFour = m.cg.getInfinitePower();

      m.cg.setInfinitePower(false);
      m.game.applyMegaStructureBonuses(1, 5);
      return { afterFour, afterFive: m.cg.getInfinitePower(), researched: m.cg.getMegaStructureTechsResearched() };
    });

    expect(result.afterFour).toBe(true);
    expect(result.afterFive).toBe(true);
    expect(result.researched).toContainEqual([1, 4]);
    expect(result.researched).toContainEqual([1, 5]);
  });

  test('Plasma Forge stages multiply every resource autobuyer rate', async ({ game }) => {
    const result = await game.withMods((m) => {
      // applyRateMultiplierToAllResources walks the four autobuyer tiers of each
      // resource — it does not touch the resource's own `rate` field, which is
      // recomputed from the autobuyers anyway. Seed nonzero tier rates so the
      // multiplication is observable rather than a no-op on zero.
      const keys = ['hydrogen', 'helium', 'carbon', 'neon', 'oxygen', 'silicon', 'iron', 'sodium'];
      const tiers = ['tier1', 'tier2', 'tier3', 'tier4'];
      const paths = [];
      for (const key of keys) {
        for (const tier of tiers) {
          const path = [key, 'upgrades', 'autoBuyer', tier, 'rate'];
          if (typeof m.rdo.getResourceDataObject('resources', path) === 'number') {
            m.rdo.setResourceDataObject(8, 'resources', path);
            paths.push(path);
          }
        }
      }
      const read = () => paths.map((path) => m.rdo.getResourceDataObject('resources', path));

      const before = read();
      m.game.applyMegaStructureBonuses(3, 1);
      const afterStage1 = read();
      m.game.applyMegaStructureBonuses(3, 5);
      const afterStage5 = read();

      return {
        pathCount: paths.length,
        before,
        afterStage1,
        afterStage5,
        bonusFlag: m.cg.getMegaStructureResourceBonus(),
        researched: m.cg.getMegaStructureTechsResearched()
      };
    });

    expect(result.pathCount).toBeGreaterThan(0);
    result.afterStage1.forEach((rate, index) => {
      expect(rate).toBeCloseTo(result.before[index] * 1.25, 6);
    });
    // Stage 5 compounds on top of stage 1 rather than replacing it.
    result.afterStage5.forEach((rate, index) => {
      expect(rate).toBeCloseTo(result.before[index] * 1.25 * 2, 6);
    });
    expect(result.bonusFlag).toBe(true);
    expect(result.researched).toContainEqual([3, 5]);
  });

  test('Galactic Memory Archive stages add storage capacity in escalating steps', async ({ game }) => {
    const result = await game.withMods((m) => {
      const read = () => ({
        hydrogen: m.rdo.getResourceDataObject('resources', ['hydrogen', 'storageCapacity']),
        titanium: m.rdo.getResourceDataObject('compounds', ['titanium', 'storageCapacity'])
      });

      const before = read();
      m.game.applyMegaStructureBonuses(4, 1);
      const afterStage1 = read();
      m.game.applyMegaStructureBonuses(4, 5);
      return {
        before,
        afterStage1,
        afterStage5: read(),
        adderFlag: m.cg.getStorageAdderBonus(),
        researched: m.cg.getMegaStructureTechsResearched()
      };
    });

    expect(result.afterStage1.hydrogen).toBe(result.before.hydrogen + 100000);
    expect(result.afterStage1.titanium).toBe(result.before.titanium + 100000);
    expect(result.afterStage5.hydrogen).toBe(result.before.hydrogen + 100000 + 10000000000);
    expect(result.adderFlag).toBe(true);
    expect(result.researched).toContainEqual([4, 5]);
  });

  test('stage 3 of every structure lowers the force field one level and permanently unlocks antimatter', async ({ game }) => {
    const result = await game.withMods((m) => {
      m.cg.setMiaplacidusMilestoneLevel(0);
      m.cg.setPermanentAntimatterUnlock(false);
      m.cg.setMegaStructureAntimatterAmount(0);

      const levels = [];
      for (const structure of [1, 2, 3, 4]) {
        m.game.applyMegaStructureBonuses(structure, 3);
        levels.push(m.cg.getMiaplacidusMilestoneLevel());
      }

      return {
        levels,
        permanentAntimatter: m.cg.getPermanentAntimatterUnlock(),
        antimatterAmount: m.cg.getMegaStructureAntimatterAmount(),
        researched: m.cg.getMegaStructureTechsResearched()
      };
    });

    // Each of the four structures takes the field down one level, so capturing
    // all four is what opens Miaplacidus.
    expect(result.levels).toEqual([1, 2, 3, 4]);
    expect(result.permanentAntimatter).toBe(true);
    // setMegaStructureAntimatterAmount accumulates rather than assigning, so the
    // four stage-3 unlocks stack into a 60% antimatter bonus, not 15%.
    expect(result.antimatterAmount).toBeCloseTo(0.6, 6);
    for (const structure of [1, 2, 3, 4]) {
      expect(result.researched).toContainEqual([structure, 3]);
    }
  });

  test('taking the force field to level four flags the endgame achievement', async ({ game }) => {
    await game.withMods((m) => {
      m.cg.setMiaplacidusMilestoneLevel(3);
      m.game.applyMegaStructureBonuses(2, 3);
    });

    // checkForAchievements() runs on the game loop, so poll the achievement's
    // own granted state rather than the transient flag array.
    await game.page.waitForTimeout(700);
    const granted = await game.withMods((m) => ({
      level: m.cg.getMiaplacidusMilestoneLevel(),
      achievement: m.rdo.getAchievementDataObject('bringDownMiaplacideanForceField')?.active
    }));

    expect(granted.level).toBe(4);
    expect(granted.achievement).toBe(true);
  });

  test('researched stages accumulate as structure/stage pairs without losing earlier ones', async ({ game }) => {
    const researched = await game.withMods((m) => {
      m.cg.setMegaStructureTechsResearched([], true);
      m.game.applyMegaStructureBonuses(2, 1);
      m.game.applyMegaStructureBonuses(2, 2);
      m.game.applyMegaStructureBonuses(2, 4);
      m.game.applyMegaStructureBonuses(2, 5);
      return m.cg.getMegaStructureTechsResearched();
    });

    expect(researched).toEqual([[2, 1], [2, 2], [2, 4], [2, 5]]);
  });

  test('an unknown structure or stage is a no-op rather than a crash', async ({ game }) => {
    const result = await game.withMods((m) => {
      m.cg.setMegaStructureTechsResearched([], true);
      m.game.applyMegaStructureBonuses(9, 1);
      m.game.applyMegaStructureBonuses(1, 99);
      m.game.applyMegaStructureBonuses(null, null);
      return m.cg.getMegaStructureTechsResearched();
    });

    expect(result).toEqual([]);
    expect(game.significantErrors()).toEqual([]);
  });

  test('the megastructure run flag and captured structures survive a save/load round trip', async ({ game }) => {
    const result = await game.withMods((m) => {
      m.cg.setCurrentRunIsMegaStructureRun(true);
      m.cg.setMegaStructureTechsResearched([[1, 1], [1, 2]], true);
      m.cg.setMegaStructuresInPossessionArray('dysonSphere');
      m.cg.setMiaplacidusMilestoneLevel(2);

      const saved = JSON.parse(JSON.stringify(m.cg.captureGameStatusForSaving('initialise')));
      return {
        megaRun: saved.flags?.currentRunIsMegaStructureRun,
        techs: saved.megaStructureTechsResearched,
        possession: saved.megaStructuresInPossessionArray,
        milestone: saved.miaplacidusMilestoneLevel,
        liveTechs: m.cg.getMegaStructureTechsResearched(),
        livePossession: m.cg.getMegaStructuresInPossessionArray()
      };
    });

    expect(result.megaRun).toBe(true);
    expect(result.techs).toEqual(result.liveTechs);
    expect(result.possession).toEqual(result.livePossession);
    expect(result.milestone).toBe(2);
  });
});
